# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    actu_paginator_num_per_page: 2

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    test_service:
        class: AppBundle\Service\TestService
        arguments: ["@doctrine", "asdf", "%database_name%"]
    actu_paginator:
        class: AppBundle\Service\ActuPaginator
        arguments: ["%actu_paginator_num_per_page%"]
