<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ActuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuRepository extends EntityRepository
{

	public function findHomeActus()
	{
		$qb = $this->createQueryBuilder("a");

		$query = $qb->where("a.isPublished = 1")
					->orderBy("a.datePublished", "DESC")
					->setMaxResults(10)
					->getQuery();

		return $query->getResult();
	}


	public function findPagedActus($page, $numPerPage = 10)
	{
		$qb = $this->createQueryBuilder("a");

		$query = $qb->orderBy("a.datePublished", "DESC")
					->setFirstResult( ($page-1)*$numPerPage )
					->setMaxResults( $numPerPage )
					->getQuery();

		$paginator = new Paginator($query);
		return $paginator;

	}

}
	